[tool.poetry]
name = "manaba-attend"
version = "0.1.0"
description = "ğŸ’» ã‚³ãƒãƒ³ãƒ‰ãƒ©ã‚¤ãƒ³ã‹ã‚‰ Manaba ã®å‡ºå¸­ã‚«ãƒ¼ãƒ‰ã‚’æå‡ºã™ã‚‹ãƒ—ãƒ­ã‚°ãƒ©ãƒ "
authors = ["TAKAHASHI Shuuji <shuuji3@gmail.com>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
beautifulsoup4 = "^4.8"
lxml = "^4.4"
pyyaml = "^5.1"
selenium = "^3.141"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
